### ISSUE TITLE
Field guide's attached images not included in project copy

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/panoptes#4238]
## Current Behavior

When the `ProjectCopier` ([link](https://github.com/zooniverse/panoptes/blob/master/app/workers/project_copy_worker.rb#L7)) is run, the field guide's attached images are not copied over. Tutorial images images are copied over (see https://github.com/zooniverse/panoptes/blob/master/lib/project_copier.rb#L13) but field guide images are not.

## Desired Behavior

Add field guide attached images to the project copier, possibly via the `INCLUDED_ASSOCIATIONS` target list.

**Comment by zwolf** [comment]
Fixed by https://github.com/zooniverse/panoptes/pull/4258

**Comment by lcjohnso** [comment]
Reopening: while media resources are cloned (good), the media item IDs in the field guide's `items` field remain unchanged, so the linked icon images still do not appear in the [lab](https://www.zooniverse.org/lab/30326/guide) for the cloned project or in the [field guide on the project](https://www.zooniverse.org/projects/american-prairie/cameras-for-conservation-ey/about/research) (bad).

Example on prod: [Cameras for Conservation](https://www.zooniverse.org/projects/american-prairie/cameras-for-conservation) / [Cameras for Conservation EY](https://www.zooniverse.org/projects/american-prairie/cameras-for-conservation-ey)
Project Source: ID=24811, https://www.zooniverse.org/lab/24811
Project Destination: ID=30326, https://www.zooniverse.org/lab/30326
Field Guide IDs = 3023 and 3140 for source and destination, respectively (note that both instances `items` values are the same)

attn: @zwolf (not high priority, but still wish this would work better)
